//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDS.FIM.Agents.ECMA2.Pifu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDS.FIM.Agents.ECMA2.Pifu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.1&quot;
        ///	targetNamespace=&quot;http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.1&quot;
        ///	xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;PIFU IMS_SAS 2014-07-04&quot;
        ///	elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.w3.org/XML/1998/namespace&quot; /&gt;
        ///
        ///	&lt;!-- Typedefinisjoner. Alle IMS-elementer skal være en av disse typene --&gt;
        ///	&lt;xs:simpleType name=&quot;t_string1&quot;&gt;
        ///		&lt;xs:restriction base=&quot;x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PIFU_IMS_SAS_1_1 {
            get {
                return ResourceManager.GetString("PIFU_IMS_SAS_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2&quot;
        ///	targetNamespace=&quot;http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2&quot;
        ///	xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;PIFU IMS_SAS 2019-06-07&quot;
        ///	elementFormDefault=&quot;qualified&quot;&gt;
        ///  &lt;xs:import namespace=&quot;http://www.w3.org/XML/1998/namespace&quot;/&gt;
        ///
        ///  &lt;!-- Typedefinisjoner. Alle IMS-elementer skal være en av disse typene --&gt;
        ///  &lt;xs:simpleType name=&quot;t_string1&quot;&gt;
        ///    &lt;xs:restriction bas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PIFU_IMS_SAS_1_2 {
            get {
                return ResourceManager.GetString("PIFU_IMS_SAS_1_2", resourceCulture);
            }
        }
    }
}
