//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class comments {
    
    private string langField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class datasource {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class datetime {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class sourcedid {
    
    private sourcedidSource sourceField;
    
    private sourcedidID idField;
    
    private sourcedidSourcedidtype sourcedidtypeField;
    
    private bool sourcedidtypeFieldSpecified;
    
    /// <remarks/>
    public sourcedidSource source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public sourcedidID id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sourcedidSourcedidtype sourcedidtype {
        get {
            return this.sourcedidtypeField;
        }
        set {
            this.sourcedidtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sourcedidtypeSpecified {
        get {
            return this.sourcedidtypeFieldSpecified;
        }
        set {
            this.sourcedidtypeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public partial class sourcedidSource {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public partial class sourcedidID {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum sourcedidSourcedidtype {
    
    /// <remarks/>
    Duplicate,
    
    /// <remarks/>
    Old,
    
    /// <remarks/>
    New,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class userid {
    
    private useridtype useridtypeField;
    
    private string passwordField;
    
    private string pwencryptiontypeField;
    
    private string authenticationtypeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public useridtype useridtype {
        get {
            return this.useridtypeField;
        }
        set {
            this.useridtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pwencryptiontype {
        get {
            return this.pwencryptiontypeField;
        }
        set {
            this.pwencryptiontypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string authenticationtype {
        get {
            return this.authenticationtypeField;
        }
        set {
            this.authenticationtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum useridtype {
    
    /// <remarks/>
    personNIN,
    
    /// <remarks/>
    personNINencrypted,
    
    /// <remarks/>
    personLIN,
    
    /// <remarks/>
    personFIN,
    
    /// <remarks/>
    studentID,
    
    /// <remarks/>
    workforceID,
    
    /// <remarks/>
    username,
    
    /// <remarks/>
    sisID,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class timeframe {
    
    private timeframeBegin beginField;
    
    private timeframeEnd endField;
    
    private string adminperiodField;
    
    /// <remarks/>
    public timeframeBegin begin {
        get {
            return this.beginField;
        }
        set {
            this.beginField = value;
        }
    }
    
    /// <remarks/>
    public timeframeEnd end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    public string adminperiod {
        get {
            return this.adminperiodField;
        }
        set {
            this.adminperiodField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public partial class timeframeBegin {
    
    private string restrictField;
    
    private System.DateTime valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string restrict {
        get {
            return this.restrictField;
        }
        set {
            this.restrictField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="date")]
    public System.DateTime Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public partial class timeframeEnd {
    
    private string restrictField;
    
    private System.DateTime valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string restrict {
        get {
            return this.restrictField;
        }
        set {
            this.restrictField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="date")]
    public System.DateTime Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class enterprise {
    
    private comments commentsField;
    
    private properties propertiesField;
    
    private person[] personField;
    
    private group[] groupField;
    
    private membership[] membershipField;
    
    /// <remarks/>
    public comments comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    public properties properties {
        get {
            return this.propertiesField;
        }
        set {
            this.propertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("person")]
    public person[] person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("group")]
    public group[] group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("membership")]
    public membership[] membership {
        get {
            return this.membershipField;
        }
        set {
            this.membershipField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class properties {
    
    private comments commentsField;
    
    private datasource datasourceField;
    
    private string[] targetField;
    
    private propertiesType typeField;
    
    private datetime datetimeField;
    
    private extension extensionField;
    
    private string langField;
    
    /// <remarks/>
    public comments comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    public datasource datasource {
        get {
            return this.datasourceField;
        }
        set {
            this.datasourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("target")]
    public string[] target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    public propertiesType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public datetime datetime {
        get {
            return this.datetimeField;
        }
        set {
            this.datetimeField = value;
        }
    }
    
    /// <remarks/>
    public extension extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum propertiesType {
    
    /// <remarks/>
    full,
    
    /// <remarks/>
    delta,
    
    /// <remarks/>
    @event,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class extension {
    
    private pifu_id[] pifu_idField;
    
    private pifu_name[] pifu_nameField;
    
    private pifu_email[] pifu_emailField;
    
    private pifu_url[] pifu_urlField;
    
    private pifu_tel[] pifu_telField;
    
    private pifu_adr[] pifu_adrField;
    
    private pifu_status[] pifu_statusField;
    
    private pifu_language pifu_preferredLanguageField;
    
    private pifu_language[] pifu_nativeTongueField;
    
    private pifu_hasContactPerson[] pifu_hasContactPersonField;
    
    private pifu_primaryRelation pifu_primaryRelationField;
    
    private bool pifu_primaryRelationFieldSpecified;
    
    private pifu_absence[] pifu_absenceField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pifu_id")]
    public pifu_id[] pifu_id {
        get {
            return this.pifu_idField;
        }
        set {
            this.pifu_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pifu_name")]
    public pifu_name[] pifu_name {
        get {
            return this.pifu_nameField;
        }
        set {
            this.pifu_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pifu_email")]
    public pifu_email[] pifu_email {
        get {
            return this.pifu_emailField;
        }
        set {
            this.pifu_emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pifu_url")]
    public pifu_url[] pifu_url {
        get {
            return this.pifu_urlField;
        }
        set {
            this.pifu_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pifu_tel")]
    public pifu_tel[] pifu_tel {
        get {
            return this.pifu_telField;
        }
        set {
            this.pifu_telField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pifu_adr")]
    public pifu_adr[] pifu_adr {
        get {
            return this.pifu_adrField;
        }
        set {
            this.pifu_adrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pifu_status")]
    public pifu_status[] pifu_status {
        get {
            return this.pifu_statusField;
        }
        set {
            this.pifu_statusField = value;
        }
    }
    
    /// <remarks/>
    public pifu_language pifu_preferredLanguage {
        get {
            return this.pifu_preferredLanguageField;
        }
        set {
            this.pifu_preferredLanguageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pifu_nativeTongue")]
    public pifu_language[] pifu_nativeTongue {
        get {
            return this.pifu_nativeTongueField;
        }
        set {
            this.pifu_nativeTongueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pifu_hasContactPerson")]
    public pifu_hasContactPerson[] pifu_hasContactPerson {
        get {
            return this.pifu_hasContactPersonField;
        }
        set {
            this.pifu_hasContactPersonField = value;
        }
    }
    
    /// <remarks/>
    public pifu_primaryRelation pifu_primaryRelation {
        get {
            return this.pifu_primaryRelationField;
        }
        set {
            this.pifu_primaryRelationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pifu_primaryRelationSpecified {
        get {
            return this.pifu_primaryRelationFieldSpecified;
        }
        set {
            this.pifu_primaryRelationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pifu_absence")]
    public pifu_absence[] pifu_absence {
        get {
            return this.pifu_absenceField;
        }
        set {
            this.pifu_absenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class pifu_id {
    
    private string pifu_valueField;
    
    private string pifu_scopeField;
    
    private pifu_unique pifu_uniqueField;
    
    private pifu_idType typeField;
    
    private bool typeFieldSpecified;
    
    /// <remarks/>
    public string pifu_value {
        get {
            return this.pifu_valueField;
        }
        set {
            this.pifu_valueField = value;
        }
    }
    
    /// <remarks/>
    public string pifu_scope {
        get {
            return this.pifu_scopeField;
        }
        set {
            this.pifu_scopeField = value;
        }
    }
    
    /// <remarks/>
    public pifu_unique pifu_unique {
        get {
            return this.pifu_uniqueField;
        }
        set {
            this.pifu_uniqueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public pifu_idType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public enum pifu_unique {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum pifu_idType {
    
    /// <remarks/>
    organizationNumber,
    
    /// <remarks/>
    municipalityNumber,
    
    /// <remarks/>
    countyNumber,
    
    /// <remarks/>
    vigoNumber,
    
    /// <remarks/>
    gsiNumber,
    
    /// <remarks/>
    domainName,
    
    /// <remarks/>
    grepCode,
    
    /// <remarks/>
    grepCodeShortForm,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class pifu_name {
    
    private string pifu_valueField;
    
    private pifu_language pifu_languageField;
    
    private pifu_nameType typeField;
    
    private bool typeFieldSpecified;
    
    /// <remarks/>
    public string pifu_value {
        get {
            return this.pifu_valueField;
        }
        set {
            this.pifu_valueField = value;
        }
    }
    
    /// <remarks/>
    public pifu_language pifu_language {
        get {
            return this.pifu_languageField;
        }
        set {
            this.pifu_languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public pifu_nameType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class pifu_language {
    
    private pifu_languageSource sourceField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public pifu_languageSource source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum pifu_languageSource {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ISO 639-1")]
    ISO6391,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ISO 639-2")]
    ISO6392,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ISO 639-2")]
    ISO63921,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum pifu_nameType {
    
    /// <remarks/>
    legalName,
    
    /// <remarks/>
    name,
    
    /// <remarks/>
    fullName,
    
    /// <remarks/>
    shortName,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class pifu_email {
    
    private pifu_emailType typeField;
    
    private bool typeFieldSpecified;
    
    private string priorityField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public pifu_emailType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum pifu_emailType {
    
    /// <remarks/>
    personEmailPrivate,
    
    /// <remarks/>
    personEmailAtOrg,
    
    /// <remarks/>
    orgEmail,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class pifu_url {
    
    private pifu_urlType typeField;
    
    private bool typeFieldSpecified;
    
    private string priorityField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public pifu_urlType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum pifu_urlType {
    
    /// <remarks/>
    personURLPrivate,
    
    /// <remarks/>
    personURLAtOrg,
    
    /// <remarks/>
    orgURL,
    
    /// <remarks/>
    orgIntranet,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class pifu_tel {
    
    private pifu_telType typeField;
    
    private bool typeFieldSpecified;
    
    private string priorityField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public pifu_telType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum pifu_telType {
    
    /// <remarks/>
    personTelephonePrivate,
    
    /// <remarks/>
    personMobilePrivate,
    
    /// <remarks/>
    personTelephoneAtOrg,
    
    /// <remarks/>
    personMobileAtOrg,
    
    /// <remarks/>
    personFaxAtOrg,
    
    /// <remarks/>
    personSwitchboard,
    
    /// <remarks/>
    orgTelephone,
    
    /// <remarks/>
    orgFax,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class pifu_adr {
    
    private adr adrField;
    
    private timeframe timeframeField;
    
    private string[] textField;
    
    private pifu_adrType typeField;
    
    private bool typeFieldSpecified;
    
    private string priorityField;
    
    /// <remarks/>
    public adr adr {
        get {
            return this.adrField;
        }
        set {
            this.adrField = value;
        }
    }
    
    /// <remarks/>
    public timeframe timeframe {
        get {
            return this.timeframeField;
        }
        set {
            this.timeframeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public pifu_adrType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class adr {
    
    private string poboxField;
    
    private string extaddField;
    
    private string[] streetField;
    
    private string localityField;
    
    private string regionField;
    
    private string pcodeField;
    
    private string countryField;
    
    /// <remarks/>
    public string pobox {
        get {
            return this.poboxField;
        }
        set {
            this.poboxField = value;
        }
    }
    
    /// <remarks/>
    public string extadd {
        get {
            return this.extaddField;
        }
        set {
            this.extaddField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("street")]
    public string[] street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string locality {
        get {
            return this.localityField;
        }
        set {
            this.localityField = value;
        }
    }
    
    /// <remarks/>
    public string region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    public string pcode {
        get {
            return this.pcodeField;
        }
        set {
            this.pcodeField = value;
        }
    }
    
    /// <remarks/>
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum pifu_adrType {
    
    /// <remarks/>
    personRegisteredAddressPrivate,
    
    /// <remarks/>
    personPostalAddressPrivate,
    
    /// <remarks/>
    personVisitorAddressAtOrg,
    
    /// <remarks/>
    personPostalAddressAtOrg,
    
    /// <remarks/>
    personPostalAddressHoliday,
    
    /// <remarks/>
    orgPostalAddress,
    
    /// <remarks/>
    orgVisitorAddress,
    
    /// <remarks/>
    orgDeliveryAddress,
    
    /// <remarks/>
    orgBillingAddress,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class pifu_status {
    
    private pifu_statusType typeField;
    
    private bool typeFieldSpecified;
    
    private pifu_status_values valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public pifu_statusType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public pifu_status_values Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum pifu_statusType {
    
    /// <remarks/>
    activeInactive,
    
    /// <remarks/>
    pupilStatus,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum pifu_status_values {
    
    /// <remarks/>
    aktiv,
    
    /// <remarks/>
    inaktiv,
    
    /// <remarks/>
    heltid,
    
    /// <remarks/>
    deltid,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("norsk-utv-i-utlandet")]
    norskutviutlandet,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("utenlandsk-utv-i-norge")]
    utenlandskutvinorge,
    
    /// <remarks/>
    voksen,
    
    /// <remarks/>
    privatist,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class pifu_hasContactPerson {
    
    private sourcedid sourcedidField;
    
    private pifu_hasContactPersonType typeField;
    
    private bool typeFieldSpecified;
    
    /// <remarks/>
    public sourcedid sourcedid {
        get {
            return this.sourcedidField;
        }
        set {
            this.sourcedidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public pifu_hasContactPersonType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum pifu_hasContactPersonType {
    
    /// <remarks/>
    nextOfKin,
    
    /// <remarks/>
    guardian,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public enum pifu_primaryRelation {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class pifu_absence {
    
    private sourcedid sourcedidField;
    
    private pifu_absence_type pifu_absence_typeField;
    
    private timeframe timeframeField;
    
    private decimal pifu_absence_valueField;
    
    private comments commentsField;
    
    private pifu_absencePifu_absence_mode pifu_absence_modeField;
    
    /// <remarks/>
    public sourcedid sourcedid {
        get {
            return this.sourcedidField;
        }
        set {
            this.sourcedidField = value;
        }
    }
    
    /// <remarks/>
    public pifu_absence_type pifu_absence_type {
        get {
            return this.pifu_absence_typeField;
        }
        set {
            this.pifu_absence_typeField = value;
        }
    }
    
    /// <remarks/>
    public timeframe timeframe {
        get {
            return this.timeframeField;
        }
        set {
            this.timeframeField = value;
        }
    }
    
    /// <remarks/>
    public decimal pifu_absence_value {
        get {
            return this.pifu_absence_valueField;
        }
        set {
            this.pifu_absence_valueField = value;
        }
    }
    
    /// <remarks/>
    public comments comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public pifu_absencePifu_absence_mode pifu_absence_mode {
        get {
            return this.pifu_absence_modeField;
        }
        set {
            this.pifu_absence_modeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class pifu_absence_type {
    
    private pifu_absence_typePifu_absence_classification pifu_absence_classificationField;
    
    private bool pifu_absence_classificationFieldSpecified;
    
    private pifu_absence_type_value valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public pifu_absence_typePifu_absence_classification pifu_absence_classification {
        get {
            return this.pifu_absence_classificationField;
        }
        set {
            this.pifu_absence_classificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pifu_absence_classificationSpecified {
        get {
            return this.pifu_absence_classificationFieldSpecified;
        }
        set {
            this.pifu_absence_classificationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public pifu_absence_type_value Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum pifu_absence_typePifu_absence_classification {
    
    /// <remarks/>
    valid,
    
    /// <remarks/>
    invalid,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum pifu_absence_type_value {
    
    /// <remarks/>
    days,
    
    /// <remarks/>
    hours,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum pifu_absencePifu_absence_mode {
    
    /// <remarks/>
    aggregate,
    
    /// <remarks/>
    occurrence,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class person {
    
    private comments commentsField;
    
    private sourcedid[] sourcedidField;
    
    private userid[] useridField;
    
    private name nameField;
    
    private demographics demographicsField;
    
    private string emailField;
    
    private string urlField;
    
    private tel[] telField;
    
    private adr adrField;
    
    private photo photoField;
    
    private extension extensionField;
    
    private recstatus recstatusField;
    
    private bool recstatusFieldSpecified;
    
    /// <remarks/>
    public comments comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sourcedid")]
    public sourcedid[] sourcedid {
        get {
            return this.sourcedidField;
        }
        set {
            this.sourcedidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("userid")]
    public userid[] userid {
        get {
            return this.useridField;
        }
        set {
            this.useridField = value;
        }
    }
    
    /// <remarks/>
    public name name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public demographics demographics {
        get {
            return this.demographicsField;
        }
        set {
            this.demographicsField = value;
        }
    }
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tel")]
    public tel[] tel {
        get {
            return this.telField;
        }
        set {
            this.telField = value;
        }
    }
    
    /// <remarks/>
    public adr adr {
        get {
            return this.adrField;
        }
        set {
            this.adrField = value;
        }
    }
    
    /// <remarks/>
    public photo photo {
        get {
            return this.photoField;
        }
        set {
            this.photoField = value;
        }
    }
    
    /// <remarks/>
    public extension extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public recstatus recstatus {
        get {
            return this.recstatusField;
        }
        set {
            this.recstatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool recstatusSpecified {
        get {
            return this.recstatusFieldSpecified;
        }
        set {
            this.recstatusFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class name {
    
    private string fnField;
    
    private nameN nField;
    
    /// <remarks/>
    public string fn {
        get {
            return this.fnField;
        }
        set {
            this.fnField = value;
        }
    }
    
    /// <remarks/>
    public nameN n {
        get {
            return this.nField;
        }
        set {
            this.nField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public partial class nameN {
    
    private string familyField;
    
    private string givenField;
    
    /// <remarks/>
    public string family {
        get {
            return this.familyField;
        }
        set {
            this.familyField = value;
        }
    }
    
    /// <remarks/>
    public string given {
        get {
            return this.givenField;
        }
        set {
            this.givenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class demographics {
    
    private demographicsGender genderField;
    
    private bool genderFieldSpecified;
    
    private System.DateTime bdayField;
    
    private bool bdayFieldSpecified;
    
    /// <remarks/>
    public demographicsGender gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool genderSpecified {
        get {
            return this.genderFieldSpecified;
        }
        set {
            this.genderFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime bday {
        get {
            return this.bdayField;
        }
        set {
            this.bdayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bdaySpecified {
        get {
            return this.bdayFieldSpecified;
        }
        set {
            this.bdayFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum demographicsGender {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class tel {
    
    private telTeltype teltypeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public telTeltype teltype {
        get {
            return this.teltypeField;
        }
        set {
            this.teltypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum telTeltype {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class photo {
    
    private string extrefField;
    
    private string imgtypeField;
    
    /// <remarks/>
    public string extref {
        get {
            return this.extrefField;
        }
        set {
            this.extrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string imgtype {
        get {
            return this.imgtypeField;
        }
        set {
            this.imgtypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum recstatus {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class group {
    
    private comments commentsField;
    
    private sourcedid[] sourcedidField;
    
    private grouptype[] grouptypeField;
    
    private description descriptionField;
    
    private timeframe timeframeField;
    
    private string emailField;
    
    private string urlField;
    
    private relationship[] relationshipField;
    
    private extension extensionField;
    
    private recstatus recstatusField;
    
    private bool recstatusFieldSpecified;
    
    /// <remarks/>
    public comments comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sourcedid")]
    public sourcedid[] sourcedid {
        get {
            return this.sourcedidField;
        }
        set {
            this.sourcedidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("grouptype")]
    public grouptype[] grouptype {
        get {
            return this.grouptypeField;
        }
        set {
            this.grouptypeField = value;
        }
    }
    
    /// <remarks/>
    public description description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public timeframe timeframe {
        get {
            return this.timeframeField;
        }
        set {
            this.timeframeField = value;
        }
    }
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("relationship")]
    public relationship[] relationship {
        get {
            return this.relationshipField;
        }
        set {
            this.relationshipField = value;
        }
    }
    
    /// <remarks/>
    public extension extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public recstatus recstatus {
        get {
            return this.recstatusField;
        }
        set {
            this.recstatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool recstatusSpecified {
        get {
            return this.recstatusFieldSpecified;
        }
        set {
            this.recstatusFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class grouptype {
    
    private grouptypeScheme schemeField;
    
    private grouptypeTypevalue typevalueField;
    
    /// <remarks/>
    public grouptypeScheme scheme {
        get {
            return this.schemeField;
        }
        set {
            this.schemeField = value;
        }
    }
    
    /// <remarks/>
    public grouptypeTypevalue typevalue {
        get {
            return this.typevalueField;
        }
        set {
            this.typevalueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum grouptypeScheme {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("pifu-ims-go-org")]
    pifuimsgoorg,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("pifu-ims-go-grp")]
    pifuimsgogrp,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public partial class grouptypeTypevalue {
    
    private string levelField;
    
    private t_groupschematypevalue valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public t_groupschematypevalue Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum t_groupschematypevalue {
    
    /// <remarks/>
    skoleeier,
    
    /// <remarks/>
    skole,
    
    /// <remarks/>
    basisgruppe,
    
    /// <remarks/>
    undervisningsgruppe,
    
    /// <remarks/>
    kontaktlærergruppe,
    
    /// <remarks/>
    trinn,
    
    /// <remarks/>
    utdanningsprogram,
    
    /// <remarks/>
    programområde,
    
    /// <remarks/>
    fag,
    
    /// <remarks/>
    foresattegruppe,
    
    /// <remarks/>
    språkopplæring,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class description {
    
    private string shortField;
    
    private string longField;
    
    private string fullField;
    
    /// <remarks/>
    public string @short {
        get {
            return this.shortField;
        }
        set {
            this.shortField = value;
        }
    }
    
    /// <remarks/>
    public string @long {
        get {
            return this.longField;
        }
        set {
            this.longField = value;
        }
    }
    
    /// <remarks/>
    public string full {
        get {
            return this.fullField;
        }
        set {
            this.fullField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class relationship {
    
    private sourcedid sourcedidField;
    
    private string labelField;
    
    private relationshipRelation relationField;
    
    private bool relationFieldSpecified;
    
    /// <remarks/>
    public sourcedid sourcedid {
        get {
            return this.sourcedidField;
        }
        set {
            this.sourcedidField = value;
        }
    }
    
    /// <remarks/>
    public string label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public relationshipRelation relation {
        get {
            return this.relationField;
        }
        set {
            this.relationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool relationSpecified {
        get {
            return this.relationFieldSpecified;
        }
        set {
            this.relationFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum relationshipRelation {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class membership {
    
    private comments commentsField;
    
    private sourcedid sourcedidField;
    
    private member[] memberField;
    
    /// <remarks/>
    public comments comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    public sourcedid sourcedid {
        get {
            return this.sourcedidField;
        }
        set {
            this.sourcedidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("member")]
    public member[] member {
        get {
            return this.memberField;
        }
        set {
            this.memberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class member {
    
    private comments commentsField;
    
    private sourcedid sourcedidField;
    
    private memberIdtype idtypeField;
    
    private role[] roleField;
    
    /// <remarks/>
    public comments comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    public sourcedid sourcedid {
        get {
            return this.sourcedidField;
        }
        set {
            this.sourcedidField = value;
        }
    }
    
    /// <remarks/>
    public memberIdtype idtype {
        get {
            return this.idtypeField;
        }
        set {
            this.idtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("role")]
    public role[] role {
        get {
            return this.roleField;
        }
        set {
            this.roleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum memberIdtype {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class role {
    
    private string subroleField;
    
    private roleStatus statusField;
    
    private comments commentsField;
    
    private datetime datetimeField;
    
    private timeframe timeframeField;
    
    private interimresult[] interimresultField;
    
    private finalresult[] finalresultField;
    
    private extension extensionField;
    
    private recstatus recstatusField;
    
    private bool recstatusFieldSpecified;
    
    private roleRoletype roletypeField;
    
    private bool roletypeFieldSpecified;
    
    /// <remarks/>
    public string subrole {
        get {
            return this.subroleField;
        }
        set {
            this.subroleField = value;
        }
    }
    
    /// <remarks/>
    public roleStatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public comments comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    public datetime datetime {
        get {
            return this.datetimeField;
        }
        set {
            this.datetimeField = value;
        }
    }
    
    /// <remarks/>
    public timeframe timeframe {
        get {
            return this.timeframeField;
        }
        set {
            this.timeframeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("interimresult")]
    public interimresult[] interimresult {
        get {
            return this.interimresultField;
        }
        set {
            this.interimresultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("finalresult")]
    public finalresult[] finalresult {
        get {
            return this.finalresultField;
        }
        set {
            this.finalresultField = value;
        }
    }
    
    /// <remarks/>
    public extension extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public recstatus recstatus {
        get {
            return this.recstatusField;
        }
        set {
            this.recstatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool recstatusSpecified {
        get {
            return this.recstatusFieldSpecified;
        }
        set {
            this.recstatusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public roleRoletype roletype {
        get {
            return this.roletypeField;
        }
        set {
            this.roletypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool roletypeSpecified {
        get {
            return this.roletypeFieldSpecified;
        }
        set {
            this.roletypeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum roleStatus {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class interimresult {
    
    private mode modeField;
    
    private values valuesField;
    
    private result resultField;
    
    private comments commentsField;
    
    private string resulttypeField;
    
    /// <remarks/>
    public mode mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    public values values {
        get {
            return this.valuesField;
        }
        set {
            this.valuesField = value;
        }
    }
    
    /// <remarks/>
    public result result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    public comments comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resulttype {
        get {
            return this.resulttypeField;
        }
        set {
            this.resulttypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class mode {
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class values {
    
    private list[] listField;
    
    private min minField;
    
    private max maxField;
    
    private valuesValuetype valuetypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("list")]
    public list[] list {
        get {
            return this.listField;
        }
        set {
            this.listField = value;
        }
    }
    
    /// <remarks/>
    public min min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
    
    /// <remarks/>
    public max max {
        get {
            return this.maxField;
        }
        set {
            this.maxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public valuesValuetype valuetype {
        get {
            return this.valuetypeField;
        }
        set {
            this.valuetypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class list {
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class min {
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class max {
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum valuesValuetype {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class result {
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2", IsNullable=false)]
public partial class finalresult {
    
    private mode modeField;
    
    private values valuesField;
    
    private result resultField;
    
    private comments commentsField;
    
    private string resulttypeField;
    
    /// <remarks/>
    public mode mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    public values values {
        get {
            return this.valuesField;
        }
        set {
            this.valuesField = value;
        }
    }
    
    /// <remarks/>
    public result result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    public comments comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resulttype {
        get {
            return this.resulttypeField;
        }
        set {
            this.resulttypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pifu.no/xsd/pifu-ims_sas/pifu-ims_sas-1.2")]
public enum roleRoletype {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("01")]
    Item01,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("02")]
    Item02,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("03")]
    Item03,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("04")]
    Item04,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("05")]
    Item05,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("06")]
    Item06,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("07")]
    Item07,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("08")]
    Item08,
}
