name: Build and publish release

on:
  push:
    tags:
      - "*"
  
  workflow_dispatch:

jobs:
  
  # create_release:
  #   name: Create release
  #   runs-on: ubuntu-latest
  #   outputs:
  #     upload_url: ${{ steps.create_release.outputs.upload_url }}
  #   steps:
  #     - name: Create release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ github.ref }}
  #         release_name: Release ${{ github.ref }}
  
  build:
    name: build and upload artifacts
    runs-on: windows-latest
    # needs: create_release

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
      
      - name: Restore Packages
        run: nuget restore PIFUExtensions.sln

      - name: Get tag
        id: get_tag
        run: echo ::set-output name=ID::${GITHUB_REF/refs\/tags\//}
        shell: bash

      - name: Build Solution
        run: |
          msbuild.exe PIFUExtensions.sln -property:platform="Any CPU" -property:Configuration="Release"
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: vigobas-pifu-ist-ma
          path: bin/release/PIFUMAExtension.dll
  publish:
    needs: build
    name: publish artifacts to github release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: vigobas-pifu-ist-ma
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: PIFUMAExtension.dll
        

    
      
 
